name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize] 

env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  run_all_tests:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'      
      - name: npm ci
        run: cd frontend && SKIP_PREFLIGHT_CHECK=true npm ci  
      - name: lint
        run: cd frontend && npm run eslint
      - name: build
        run: cd frontend && SKIP_PREFLIGHT_CHECK=true npm run build
      - name: test
        run: cd frontend && CI=true npm test
      - name: backend testmode
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
          PORT: 3001
        run: SKIP_PREFLIGHT_CHECK=true npm ci && npm run start:test &
      - name: e2e test
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          command: npm run test:e2e
          wait-on: http://localhost:3001
  deploy:
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }} 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "bloglistcicd"
          heroku_email: "ttu91@hotmail.com"
          healthcheck: "https://bloglistcicd.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: action-slack-success
        if:  success()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

